[build]
  command = "npm run build"
  publish = "dist"
[[edge_functions]]
  function = "test-edge"
  path = "/test-edge"
[[edge_functions]]
  function = "generate-og-image"
  path = "/generate-og-image"
[[edge_functions]]
  function = "ssr-og-tags"
  path = "/post/*"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
